# Variabili globali
globals:
    - id: mdi_arrow_up
      type: std::string
      initial_value: '"\U000F0737"'
    - id: mdi_arrow_down
      type: std::string
      initial_value: '"\U000F072E"'
    - id: mdi_check
      type: std::string
      initial_value: '"\U000F0E1E"'

# Include file esterni per organizzazione modulare
packages:
    lvgl_ui: !include include/lvgl_config.yaml
    anthurium1: !include
        file: include/plant_sensors.yaml
        vars:
            prefix: plant1
            entity_prefix: sensor.plant_sensor_b90c
            light: [1, 10000]
            conductivity: [250, 2000]
            temperature: [15.0, 32.0]
            humidity: [16, 65]
    anthurium2: !include
        file: include/plant_sensors.yaml
        vars:
            prefix: plant2
            entity_prefix: sensor.plant_sensor_a299
            light: [1, 10000]
            conductivity: [250, 2000]
            temperature: [15.0, 32.0]
            humidity: [16, 65]
    alstroemeria: !include
        file: include/plant_sensors.yaml
        vars:
            prefix: plant3
            entity_prefix: sensor.plant_sensor_b90a
            light: [1, 10000]
            conductivity: [350, 2000]
            temperature: [8.0, 32.0]
            humidity: [15, 60]
    graptoseum: !include
        file: include/plant_sensors.yaml
        vars:
            prefix: plant4
            entity_prefix: sensor.plant_sensor_b90e
            light: [1, 10000]
            conductivity: [300, 1000]
            temperature: [5.0, 35.0]
            humidity: [7, 50]
esphome:
    name: plantdisplay
    friendly_name: PlantDisplay
    min_version: "2025.4.2"
    platformio_options:
        build_flags: "-DBOARD_HAS_PSRAM"
        board_build.arduino.memory_type: qio_opi
        board_build.flash_mode: dio
        board_upload.maximum_ram_size: 524288
    on_boot:
        priority: 600
        then:
            - delay: 2s
            - logger.log: "Boot delay completed"
            - delay: 1s
            - light.turn_on: lcdbacklight
            - delay: 500ms
            - logger.log: "Starting display initialization"
            - delay: 3s
            - lvgl.page.show: main_page
            - logger.log: "Display initialized successfully"

psram:
    mode: octal
    speed: 80MHz

esp32:
    board: esp32-s3-devkitc-1
    variant: ESP32S3
    flash_size: 8MB
    framework:
        type: esp-idf
        advanced:
            enable_idf_experimental_features: true
        sdkconfig_options:
            COMPILER_OPTIMIZATION_SIZE: y
            CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
            CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
            CONFIG_FREERTOS_HZ: "1000"
            CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
            CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
            CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
            CONFIG_SPIRAM_MODE_OCT: y
            CONFIG_IDF_EXPERIMENTAL_FEATURES: y
            CONFIG_SPIRAM_SPEED_80M: y
            CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
            CONFIG_SPIRAM_RODATA: y
            CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
            CONFIG_COMPILER_OPTIMIZATION_PERF: y

i2c:
    sda: GPIO08
    scl: GPIO09
    scan: True
    id: bus_a

ch422g:
    - id: ch422g_hub

output:
    - platform: gpio
      id: lcdbacklight_output
      pin:
          ch422g: ch422g_hub
          number: 2
          mode:
              output: true
          inverted: false

light:
    - platform: binary
      output: lcdbacklight_output
      id: lcdbacklight
      name: LCD Backlight
      icon: mdi:wall-sconce-flat-outline
      restore_mode: ALWAYS_ON
      on_turn_off:
          - script.execute: start_antiburn
      on_turn_on:
          - script.execute: stop_antiburn

script:
    - id: start_antiburn
      then:
          - delay: 5min
          - logger.log: Starting automatic antiburn.
          - switch.turn_on: switch_antiburn
    - id: stop_antiburn
      then:
          - script.stop: start_antiburn
          - switch.turn_off: switch_antiburn

switch:
    - platform: template
      name: Antiburn
      id: switch_antiburn
      icon: mdi:television-shimmer
      optimistic: true
      entity_category: "config"
      turn_on_action:
          - logger.log: "Starting Antiburn"
          - if:
                condition: lvgl.is_paused
                then:
                    - lvgl.resume:
                    - lvgl.widget.redraw:
          - lvgl.pause:
                show_snow: true
      turn_off_action:
          - logger.log: "Stopping Antiburn"
          - if:
                condition: lvgl.is_paused
                then:
                    - lvgl.resume:
                    - lvgl.widget.redraw:

### Display
display:
    - platform: rpi_dpi_rgb
      id: waveshare_display
      update_interval: never
      auto_clear_enabled: false
      color_order: RGB
      pclk_frequency: 16MHZ
      dimensions:
          width: 800
          height: 480
      de_pin:
          number: 5
      hsync_pin:
          number: 46
          ignore_strapping_warning: true
      vsync_pin:
          number: 3
          ignore_strapping_warning: true
      pclk_pin: 7
      pclk_inverted: true
      reset_pin:
          ch422g: ch422g_hub
          number: 3
      hsync_back_porch: 8
      hsync_front_porch: 8
      hsync_pulse_width: 4
      vsync_back_porch: 16
      vsync_front_porch: 16
      vsync_pulse_width: 4
      data_pins:
          red:
              - 1 #r3
              - 2 #r4
              - 42 #r5
              - 41 #r6
              - 40 #r7
          blue:
              - 14 #b3
              - 38 #b4
              - 18 #b5
              - 17 #b6
              - 10 #b7
          green:
              - 39 #g2
              - 0 #g3
              - 45 #g4
              - 48 #g5
              - 47 #g6
              - 21 #g7

### Touchscreen
touchscreen:
    platform: gt911
    id: waveshare_touch
    interrupt_pin: GPIO4
    reset_pin:
        ch422g: ch422g_hub
        number: 1
        mode: OUTPUT

# Enable logging
logger:
    # level: VERY_VERBOSE

# Configurazioni di rete e API incluse da secrets.yaml

esp32_ble_tracker:
    scan_parameters:
        # We currently use the defaults to ensure Bluetooth
        # can co-exist with WiFi In the future we may be able to
        # enable the built-in coexistence logic in ESP-IDF
        active: true

bluetooth_proxy:
    active: true

time:
    - platform: homeassistant
      on_time:
          - hours: 2,3,4,5
            minutes: 5
            seconds: 0
            then:
                - switch.turn_on: switch_antiburn
          - hours: 2,3,4,5
            minutes: 35
            seconds: 0
            then:
                - switch.turn_off: switch_antiburn

# Configurazioni WiFi
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    power_save_mode: light
    # # Configurazioni aggiuntive per stabilità
    # reboot_timeout: 15min
    # output_power: 20dB
    # fast_connect: true
    # # Fallback hotspot in caso di problemi di connessione
    # ap:
    #     ssid: "PlantDisplay Fallback"
    #     password: "plantdisplay123"

# Enable Home Assistant API
api:
    encryption:
        key: !secret plantdisplay_api_key
    # Configurazioni per migliorare la stabilità della connessione
    # reboot_timeout: 15min
    # services:
    #     - service: force_update_sensors
    #       then:
    #           - logger.log: "Forced sensor update requested"

# OTA Updates
ota:
    - platform: esphome
      password: !secret plantdisplay_ota_password

# Sensori per climatizzatori - utilizziamo text_sensor per lo stato completo
text_sensor:
#     - platform: homeassistant
#       name: "Soggiorno Climate State"
#       id: soggiorno_climate
#       entity_id: climate.soggiorno
#       on_value:
#           then:
#               - lvgl.label.update:
#                     id: ac1_temp_label
#                     text: "Stato: CONNESSO"
#               - lvgl.label.update:
#                     id: ac1_target_label
#                     text: "Ready"
#
#     - platform: homeassistant
#       name: "Camera Climate State"
#       id: camera_climate
#       entity_id: climate.camera
#       on_value:
#           then:
#               - lvgl.label.update:
#                     id: ac2_temp_label
#                     text: "Stato: CONNESSO"
#               - lvgl.label.update:
#                     id: ac2_target_label
#                     text: "Ready"
#
#     - platform: homeassistant
#       name: "Chris Climate State"
#       id: chris_climate
#       entity_id: climate.chris
#       on_value:
#           then:
#               - lvgl.label.update:
#                     id: ac3_temp_label
#                     text: "Stato: CONNESSO"
#               - lvgl.label.update:
#                     id: ac3_target_label
#                     text: "Ready"
#
